---
- ignore:
    name: "Use <$>"

- ignore:
    name: "Avoid lambda using `infix`"

- ignore:
    name:
      - "Use min"
      - "Use max"
      - "Use /="
      - "Use <="
    within: "Unit.TestUtils"
