---
resolver: nightly-2025-02-18
packages:
  - .
ghc-options:
  "$locals": -Wall -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wpartial-fields
    -Wprepositive-qualified-module
    -Wredundant-constraints
    -Wunused-binds
    -Wunused-packages
    -Wunused-type-patterns
    -Wno-missing-import-lists
    -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2@sha256:4251503bde7549e267bd307f4b293c8c0ac48c6585968108e3e3fc5a3cfbb179,1312
  - gitrev-typed-0.1@sha256:905b696dec9c52486290cfef2d3156420de83f5b21bfb0821a37822f40ee1568,3783
  - regression-simple-0.2.1@sha256:a6338a5a048db419cde21fb403df9f4df3508145f939350a15b3e0b9d8ee39d7,2319
  - tasty-bench-fit-0.1.1@sha256:f9f231d793590d5a1a3b1c455004712c7468b6c6953aa129c4961e38dd8a2f9a,1810
  - text-display-1.0.0.0@sha256:17d5a404f51ce40ba22327bdc6688fd239f66d0aa056b8d5cb83974d1dc706e5,2772
  - git: https://github.com/tbidne/algebra-simple.git
    commit: 37ec7127fbd0f591d4539e4bf72a0badd7569181
  - git: https://github.com/tbidne/bounds.git
    commit: b7ca541cfdd8564bcebe5d38456fe7abf77885b8
  - git: https://github.com/tbidne/effectful-libs.git
    commit: 0905d55e20da3fc926fa2a8b6c4b5cb120194b2a
    subdirs:
      - lib/concurrent-effectful
      - lib/effectful-utils
      - lib/fs-effectful
      - lib/ioref-effectful
      - lib/logger-effectful
      - lib/logger-ns-effectful
      - lib/optparse-effectful
      - lib/terminal-effectful
      - lib/time-effectful
      - lib/typed-process-dynamic-effectful
  - git: https://github.com/tbidne/exception-utils.git
    commit: e28b28ae3bc90a0336abf69eff28369b790f4e13
  - git: https://github.com/tbidne/fs-utils.git
    commit: 2389f7dbe5b94f65bd22088f4e5a5f6644caaade
  - git: https://github.com/tbidne/relative-time.git
    commit: b8d4703fe4d60a0cb1904cb3a0946f89a1324c7b
  - git: https://github.com/tbidne/smart-math.git
    commit: acc3d79b82830397979f4be7b45266f5fc056cfb
allow-newer: true
allow-newer-deps:
  - path
  - regression-simple
