# Only used for garmin activities.csv. Ignored for custom runs.toml.
[garmin]
unit = 'km'

[[charts]]
title = 'Runs by distance'
y-axis = 'distance'
description = 'This is some runs plotted by distance.'

[[charts]]
title = 'Runs by distance and pace'
y-axis = 'distance'
y1-axis = 'pace'
description = 'The same runs as before, but in miles.'
unit = "mi"

# Only takes runs with label 'marathon'
[[charts]]
title = 'Marathons'
filters = ['label marathon', 'datetime >= 2024']
y-axis = 'duration'
y1-axis = 'pace'

# Takes runs w/ label 'official' but __not__ marathon.
[[charts]]
title = 'Official non-marathons'
filters = ['label official', 'not label marathon']
y-axis = 'pace'

# Takes half-marathon and marathon
[[charts]]
title = 'Marathons and half-marathons'
filters = ['label half-marathon or label marathon']
y-axis = 'pace'

# Longer runs
[[charts]]
title = 'Long runs'
filters = ['distance >= 25 km']
y-axis = 'distance'
y1-axis = 'pace'

# We can optionally specify the chart type. 'default' is the same as leaving
# it off.
[charts.type]
name = 'default'

# Runs aggregated by week
[[charts]]
title = 'Runs by week'
y-axis = 'distance'

# The 'sum' type sums all runs for a certain time period. Valid periods are
# 'year', 'month', and 'week'.
[charts.type]
name = 'sum'
period = 'week'
