[[charts]]
title = 'Runs by distance'
y-axis = 'distance'
description = 'This is some runs plotted by distance.'

[[charts]]
title = 'Runs by distance and pace'
y-axis = 'distance'
y1-axis = 'pace'
description = 'The same runs as before, but in miles.'
unit = "mi"

# Only takes runs with label 'marathon'
[[charts]]
title = 'Marathons'
filters = ['label marathon']
y-axis = 'duration'
y1-axis = 'pace'

# Takes runs w/ label 'official' but __not__ marathon.
[[charts]]
title = 'Official non-marathons'
filters = ['label official', 'not (label marathon)']
y-axis = 'pace'

# Takes half-marathon and marathon
[[charts]]
title = 'Marathons and half-marathons'
filters = ['or (label half-marathon) (label marathon)']
y-axis = 'pace'
