[garmin]
unit = 'km'

[[charts]]
title = 'Runs by distance'
y-axis = 'distance'
description = 'This is some runs plotted by distance.'

[[charts]]
title = 'Runs by distance and pace'
y-axis = 'distance'
y1-axis = 'pace'
description = 'The same runs as before, but in miles.'
unit = "mi"

[[charts]]
title = 'Long runs'
filters = ['datetime >= 2024']
y-axis = 'distance'
y1-axis = 'pace'
