---
name: ci

on: # yamllint disable-line rule:truthy rule:comments
  push:
    branches:
      - main
      - release

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  CABAL_VERS: "3.12"
  GHC_VERS: "9.10.1"
  CABAL_PROJ: "cabal.ghc9101.project"
  PACER_VERS: "0.1"

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - vers: "9.10.1"
            proj_file: "--project-file cabal.ghc9101.project"
          - vers: "9.12.1"
            proj_file: ""
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc.vers }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build frontend
        run: |
          cd web
          npm install --save
          npm run build

      - name: Configure
        run: cabal configure ${{ matrix.ghc.proj_file }} --enable-tests --ghc-options -Werror

      - name: Build
        run: cabal build ${{ matrix.ghc.proj_file }} exe:pacer

      - name: Unit tests
        id: unit
        run: cabal test ${{ matrix.ghc.proj_file }} pacer:unit --test-options '--hedgehog-tests 1000000 --size-cutoff 100000'

      - name: Functional tests
        id: functional
        run: cabal test ${{ matrix.ghc.proj_file }} pacer:functional --test-options '--size-cutoff 100000'

      - name: End to end tests
        shell: bash
        run: RUN_E2E=1 cabal test ${{ matrix.ghc.proj_file }} pacer:e2e

      - name: Complexity tests
        shell: bash
        run: RUN_BENCH_FIT=1 cabal test bench-fit

      - name: Benchmarks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: bench
        run: |
          cabal bench ${{ matrix.ghc.proj_file }} --benchmark-options '
            +RTS -T -RTS
            -t100
            --csv bench/app/${{ matrix.os }}_${{ matrix.ghc.vers }}_ci.csv
            --svg bench/app/${{ matrix.os }}_${{ matrix.ghc.vers }}_ci.svg
            --baseline bench/app/baseline_${{ matrix.os }}_${{ matrix.ghc.vers }}_ci.csv
            --fail-if-slower 20
            --fail-if-faster 20'

      - uses: actions/upload-artifact@v4
        name: Bench upload
        if: ${{ failure() && steps.bench.conclusion == 'failure' }}
        with:
          name: bench_artifacts_${{ matrix.os }}_${{ matrix.ghc.vers }}
          path: |
            bench/app/${{ matrix.os }}_${{ matrix.ghc.vers }}_ci.csv
            bench/app/${{ matrix.os }}_${{ matrix.ghc.vers }}_ci.svg

  stack:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build frontend
        run: |
          cd web
          npm install --save
          npm run build

      - name: Build
        run: stack build --ghc-options -Werror

      - name: Unit tests
        id: unit
        run: stack test pacer:test:unit --ghc-options -Werror --test-arguments '--hedgehog-tests 1000000'

      - name: Functional tests
        id: functional
        run: stack test pacer:test:functional --ghc-options -Werror

      - name: End to end tests
        shell: bash
        run: RUN_E2E=1 stack test pacer:test:e2e --ghc-options -Werror

  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Compile & run tests
        run: nix build -L

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always

      - name: Lint
        run: nix run .#lint

  release:
    needs: [cabal, stack, nix, lint]
    if: github.ref == 'refs/heads/release'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: "macos-13"
            os: "macos-13"
            script: ".github/scripts/release_osx.sh"
            script_args: ""

          - name: "macos-14"
            os: "macos-14"
            script: ".github/scripts/release_osx.sh"
            script_args: ""

          - name: "macos-15"
            os: "macos-15"
            script: ".github/scripts/release_osx.sh"
            script_args: ""

          - name: "alpine_amd64"
            os: "ubuntu-24.04"
            script: ".github/scripts/release_linux.sh"
            script_args: "alpine_amd64"

          - name: "alpine_arm64v8"
            os: "ubuntu-24.04-arm"
            script: ".github/scripts/release_linux.sh"
            script_args: "alpine_arm64v8"

          - name: "windows-2025"
            os: "windows-2025"
            script: ".github/scripts/release_windows.sh"
            script_args: "2025"

          - name: "windows-2022"
            os: "windows-2022"
            script: ".github/scripts/release_windows.sh"
            script_args: "2022"

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify env vars
        run: .github/scripts/verify_env.sh

      - uses: docker/setup-docker-action@v4
        if: ${{ matrix.platform.name == 'alpine_amd64' || matrix.platform.name == 'alpine_arm64v8' }}

      # So we have sha256sum
      - name: Install coreutils
        if: ${{ matrix.platform.os == 'macos-13' || matrix.platform.os == 'macos-14' }}
        run: brew install coreutils

      - uses: haskell-actions/setup@v2
        if: ${{ matrix.platform.name != 'alpine_amd64' && matrix.platform.name != 'alpine_arm64v8' }}
        with:
          ghc-version: ${{ env.GHC_VERS }}
          cabal-version: ${{ env.CABAL_VERS }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build frontend
        if: ${{ matrix.platform.name != 'alpine_amd64' && matrix.platform.name != 'alpine_arm64v8' }}
        run: |
          cd web
          echo "*** Installing nodejs deps ***"
          npm install --save
          echo "*** Building frontend ***"
          npm run build

      - name: Install binary
        shell: bash
        run: |
          ${{ matrix.platform.script }} ${{ matrix.platform.script_args }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ matrix.platform.name }}
          path: pacer*.zip
          retention-days: 1

  merge-releases:
    runs-on: "ubuntu-latest"
    needs: release
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: release-artifacts
          pattern: release-artifacts-*
          delete-merged: true
          retention-days: 1
